added poster judges
RSEAA/RSEAA.github.io pull request #113
Opened 2024-06-21 08:31 UTC by chrismpr86

2024-06-21 08:51 UTC, rowlandm requested changes
All the new things talk about the regular organising committee....

2024-06-21 08:53 UTC, rowlandm reviewed
Can the secretary be before the others please?

And where is the session chair expectations? I couldn't find them.

2024-06-21 08:53 UTC, rowlandm commented on volunteering.md
> +The expectations of the regular organising committee members are:
This is for poster judges

2024-06-21 08:53 UTC, rowlandm commented on volunteering.md
> +The expectations of the regular organising committee members are:
This is for observers. This was a mistake from before.

2024-06-22 11:40 UTC, chrismpr86 commented
you can review now, thanks :)

2024-06-22 11:43 UTC, rowlandm approved these changes

2024-06-22 11:43 UTC, merged